// A4 — write build provenance (git commit + build date) into build-info.js.
// Prefers Vercel's VERCEL_GIT_COMMIT_SHA; falls back to local git, then "local".
import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const REPO = "https://github.com/rachelzh-hua/gse332551-reanalysis";

function git(cmd, fallback) {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return fallback;
  }
}

const full = process.env.VERCEL_GIT_COMMIT_SHA || git("git rev-parse HEAD", "");
const sha = full ? full.slice(0, 7) : "local";
const info = {
  sha,
  full,
  date: new Date().toISOString().slice(0, 10),
  commit: full ? `${REPO}/commit/${full}` : REPO,
};
writeFileSync(
  new URL("./build-info.js", import.meta.url),
  `// Generated by stamp.mjs at build time.\nwindow.NF_BUILD = ${JSON.stringify(info)};\n`
);
console.log(`stamped build-info.js: ${sha} @ ${info.date}`);
